image: maven:3.9.6-eclipse-temurin-21
stages:
    - build
    - test
caches:
    paths:
        - .m2/repository
build_job:
    stage: build
    script: 
        - echo "start compile source and packing with java_21"
        - mvn clean package -DskipTests
    artifacts:
      paths:
       - targets/*.jar
      expire_in: 1 hour
test_job:
    stage: test
    script:
    - echo "Bắt đầu chạy Unit Test..."
    - mvn test


