spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=nguyenminhqua

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=banking-super-secret-key-must-be-at-least-256-bits-long-for-hmac-sha
jwt.expiration-ms=86400000

# 1. Vietcombank Configuration
banking.provider.vcb.base-url=https://api.vcb.com.vn/sandbox
banking.provider.vcb.api-key=VCB-APP-ID-12345
banking.provider.vcb.api-secret=VCB-SECRET-KEY-ABCDE

# 2. Techcombank Configuration
banking.provider.tcb.base-url=https://api.tcb.com.vn/sandbox
banking.provider.tcb.api-key=TCB-APP-ID-12345
banking.provider.tcb.api-secret=TCB-SECRET-KEY-ABCDE

# 3. MBBank Configuration
banking.provider.mb.base-url=https://api.mbbank.com.vn/sandbox
banking.provider.mb.api-key=MB-APP-ID-12345
banking.provider.mb.api-secret=MB-SECRET-KEY-ABCDE

# 4. BIDV Configuration
banking.provider.bidv.base-url=https://api.bidv.com.vn/sandbox
banking.provider.bidv.api-key=BIDV-APP-ID-12345
banking.provider.bidv.api-secret=BIDV-SECRET-KEY-ABCDE

# 5. VPBank Configuration
banking.provider.vp.base-url=https://api.vpbank.com.vn/sandbox
banking.provider.vp.api-key=VP-APP-ID-12345
banking.provider.vp.api-secret=VP-SECRET-KEY-ABCDE

# 6. ACB Configuration
banking.provider.acb.base-url=https://api.acb.com.vn/sandbox
banking.provider.acb.api-key=ACB-APP-ID-12345
banking.provider.acb.api-secret=ACB-SECRET-KEY-ABCDE
