spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=nguyenminhqua

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=banking-super-secret-key-must-be-at-least-256-bits-long-for-hmac-sha
jwt.expiration-ms=86400000

# External Bank Configuration 
banking.provider.mb.base-url=https://api.mbbank.com.vn/sandbox
banking.provider.mb.api-key=MB-APP-ID-12345
banking.provider.mb.api-secret=MB-SECRET-KEY-ABCDE

#KAFKA CONFIG
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-banking-group
spring.kafka.consumer.auto-offset-reset=earliest

#FORMAT DATA
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:minhqua.workdev@gmail.com}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true